# GTZAN genre classification
runner:
  total_steps: 10000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 200
  eval_step: 200
  save_step: 200
  max_keep: 1
  eval_dataloaders:
    - valid
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 6.0e-3

scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 2000

downstream_expert:
  datarc:
    file_path: /workspace/audio_data/GTZAN
    meta_data: /workspace/audio_data/GTZAN
    num_workers: 8
    train_batch_size: 64
    eval_batch_size: 12
    sample_rate: 24000

  modelrc:
    projector_dim: 256
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
